### PR TITLE
Added Some more methods to make the ui components more customizable. 

### PR DESCRIPTION
**Pull request by RobinKumar5986**
Hi I hope this methods make this components more customizable and more dynamic. I future I would like to contribute more.
I wish to develop such library for jetpackCompose.

### CODE REVIEW

**Comment by kojofosu** [comment]
@RobinKumar5986  nice! Kindly update the README to include the new methods

**Comment by RobinKumar5986** [comment]
ok I will Update it

**Comment by RobinKumar5986** [comment]
Hi I have updated the README.

**Comment by kojofosu** [comment]
Thanks for the contribution

**Pull request merged**
